[build]
  command = "sed -i 's|BACKEND_URL_PLACEHOLDER|'$BACKEND_API_URL'|g' public/_redirects && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

# 重定向规则在 public/_redirects 文件中配置